---
title: "Acknowledgements"
---
  
RSwitch wasn't my idea. It's been around forever on the [R for macOS Developer's Page](http://mac.r-project.org/) but stopped working on Catalina since it hadn't been updated in ages, was only 32-bit (which is a no-go for Catalina), and had no available source code to modify.

Despite having found and old-old copy of the source code by hacking URLs via the Internet Archive, none of that code was used to make this incarnation of RSwitch.

RSwitch uses three external frameworks to accomplish its tasks:

- [Just](https://github.com/dduan/Just) by Daniel Duan
- [ProcInfo](https://github.com/objective-see/ProcInfo) by the infamous Patrick Wardle
- [VersionCompare](https://github.com/DragonCherry/VersionCompare/) by DragonCherry

The current (but, likely not final) app icon and menubar icon is based on the ['dial' Noun Project font icon](https://thenounproject.com/search/?q=dial&i=866019#) created by Icon Mark.

## Extra Credits

Many thanks to the following folks for their contributions to the project to help make RSwitch better for everyone:

- [Benjamin Guiastrennec](https://github.com/guiastrennec) for suggesting improvements to the documentation regarding how to use the installer packages from the [R for macOS Developer's Page](https://mac.r-project.org/) without clobbering existing R Framework installs.
- [Xavier Adam](https://github.com/xvrdm) for [adding books to the RSwitch library](https://github.com/hrbrmstr/RSwitch/pull/4).
